# Dependabot config for Framework

version: 2
updates:
  # root
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # landing-site
  - package-ecosystem: "npm"
    directory: "/packages/landing-site/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # site
  - package-ecosystem: "npm"
    directory: "/packages/site/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # system
  - package-ecosystem: "npm"
    directory: "/packages/system/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
